CREATE TABLE SC_TACTICS (
  TACTICS_ID   NUMBER(8) PRIMARY KEY,
  TACTICS_NAME VARCHAR2(300) NOT NULL UNIQUE,
  STATUS       NUMBER(2) DEFAULT 0,
  JAR_PATH     VARCHAR2(1024),
  CLASS_NAME   VARCHAR2(1024),
  CREATE_TIME  DATE      DEFAULT SYSDATE,
  DESCRIBE     VARCHAR2(1024)
);
CREATE SEQUENCE SEQ_SC_TACTICS
MINVALUE 1
MAXVALUE 99999999
START WITH 11
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE TABLE SC_TASK_TAG (
  TAG_ID      NUMBER(8) PRIMARY KEY,
  TAG_NAME    VARCHAR2(300) NOT NULL UNIQUE,
  CREATE_TIME DATE DEFAULT SYSDATE
);
CREATE SEQUENCE SEQ_SC_TASK_TAG
MINVALUE 1
MAXVALUE 99999999
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE TABLE SC_TASK (
  TASK_ID     NUMBER(8) PRIMARY KEY,
  TAG_ID      NUMBER(8) DEFAULT 0,
  TASK_NAME   VARCHAR2(300) NOT NULL UNIQUE,
  TASK_TYPE   NUMBER(2) DEFAULT 0,
  CIRCULATION NUMBER(2) DEFAULT 0,
  STATUS      NUMBER(2) DEFAULT 0,
  DESCRIBE    VARCHAR2(1024),
  CREATE_TIME DATE      DEFAULT SYSDATE
);
CREATE SEQUENCE SEQ_SC_TASK
MINVALUE 1
MAXVALUE 99999999
START WITH 11
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE TABLE SC_TASK_DETAIL (
  DETAIL_ID      NUMBER(8) PRIMARY KEY,
  TASK_ID        NUMBER(8) DEFAULT 0,
  TACTICS_ID     NUMBER(8) DEFAULT 0,
  CHARSET        VARCHAR2(64),
  URL_HOST       VARCHAR2(128),
  URL_PATH       VARCHAR2(2000),
  URL_PARAMS     CLOB,
  REQUEST_HEADER CLOB,
  START_TIME     VARCHAR2(64),
  END_TIME       VARCHAR2(64),
  SLEEP_TIME     NUMBER(8) DEFAULT 0,
  PARSE_TYPE     NUMBER(2) DEFAULT 0,
  PARSE_DETAIL   CLOB,
  STOP_FLOOR     CLOB
);
ALTER TABLE SC_TASK_DETAIL
  ADD CONSTRAINT FK_TASK_DETAIL_ID FOREIGN KEY (TASK_ID) REFERENCES SC_TASK (TASK_ID) ON DELETE CASCADE;

CREATE TABLE SC_BAIDU_AK (
  BAIDU_AK    VARCHAR2(64) PRIMARY KEY,
  STATUS      NUMBER(2) DEFAULT 0,
  CREATE_TIME DATE      DEFAULT SYSDATE
);

CREATE TABLE SC_ERROR_INFO (
  CODE        VARCHAR2(10) DEFAULT '-1',
  TASK_ID     NUMBER(8)    DEFAULT 0,
  RESULT_TYPE NUMBER(2),
  URL_PATH    VARCHAR2(2000),
  TABLE_NAME  VARCHAR2(64),
  DESCRIBE    CLOB,
  CREATE_TIME DATE         DEFAULT SYSDATE
);